server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 111111
  redis:
    host: localhost
  rabbitmq:
    host: localhost
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true